name: attraction
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=0.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^0.1.3
  pin_code_fields: 
  firebase_core: 
  cloud_firestore: ^0.13.4+2
  firebase_auth: 
  email_validator: ^1.0.4
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/background.jpg
